# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: echo "hello world"
      
  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      
      # run tests!
      - run: vendor/bin/phpunit
      - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
      - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml tests
      - store_test_results:
          path: /tmp/test-results.xml
      - store_artifacts:
          path: test-results.xml
          prefix: tests
          
 workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
